factorize checks

diff --git a/commons b/commons
--- a/commons
+++ b/commons
@@ -22,18 +22,13 @@ dir=`dirname $0`
 filter="$dir/count.py 2"
 
 # sanity checks
-
-if ! type -p sadf > /dev/null; then
-    echo "sadf not found. Correct your path" 1>&2
-    exit 1
-fi
-
-if ! type -p gnuplot > /dev/null; then
-    echo "gnuplot not found. Correct your path" 1>&2
-    exit 1
-fi
-
-# for gnuplot:
+for c in sadf gnuplot; do
+    if ! type -p $c > /dev/null; then
+	echo "$c not found. Correct your path" 1>&2
+	echo $PATH
+	exit 1
+    fi
+done
 
 common="set xlabel \"Time\"
 set datafile separator \";\""
